development:
  adapter: redis
  url: redis://<%= ENV["REDIS_HOST"] %>:6379/1
  channel_prefix: omnistore_development

test:
  adapter: async

staging:
  adapter: redis
  url: redis://<%= ENV["REDIS_HOST"] %>:6379/1
  channel_prefix: omnistore_staging

production:
  adapter: redis
  url: redis://<%= ENV["REDIS_HOST"] %>:6379/1
  channel_prefix: omnistore_production
